#!/usr/bin/perl
use strict;
use warnings;

use Mock::Populate;
use SVG;

my $w = 200;
my $svg = SVG->new( width => $w, height => $w );

my $g = $svg->group(
    id    => 'group',
    style => {
        stroke           => 'gray',
        fill             => 'none',
        'stroke-width'   => '0.5',
        'stroke-opacity' => '0.5',
    },
);

my $offset = $w / 2;
$g->rectangle(
    x      => 0,
    y      => 0,
    width  => $offset,
    height => $offset,
    id     => 'quadrant_0x0',
);
$g->rectangle(
    x      => $offset,
    y      => $offset,
    width  => $offset,
    height => $offset,
    id     => 'quadrant_1x1',
);

my $i = 10;
for my $j ( 0 .. 10 ) {
    $g->circle(
        cx => $offset,
        cy => $offset,
        r  => $i * $j,
        id => 'circle_' . $i . '_' . $j,
    );
}

my $n = 90;
my $x = Mock::Populate::distributor(type => 'u', prec => 4, dof => 2, N => $n);
my $y = Mock::Populate::distributor(type => 's', prec => 4, dof => 2, N => $n);

for my $j (0 .. @$x - 1) {
    $g->circle(
        cx => $x->[$j] * 10 + $offset,
        cy => $y->[$j] * 10 + $offset,
        r  => '0.5',
        id => 'circle_' . $i . 'x' . $j,
    );
}

print $svg->xmlify;
