#!/usr/bin/perl
use strict;
use warnings;
use lib '/Users/gene/bin/SVG-Graph-Kit/lib';
use SVG::Graph::Kit;

my $x = shift || 20;
@ARGV = '/Users/gene/bin/math/primes/0000002_611953.txt';

my $i = 0;
my @x = ();
push @x, $_ while ($_ = <>) =~ s/\D//g && ++$i <= $x;

my $y = $x[-1];
my $s = $x / $y;
my $sinv = $y / $x;

$i = 0;
my $d = [ map { [ ++$i, $_ ] } @x ];

my $g = SVG::Graph::Kit->new(
    _axis => {
        grid => 1, x => $x, y => $y, ys => $sinv,
        ylabels => [ map { sprintf '%.2f', $_ * $sinv } 0 .. $x ],
    },
    _items => [
        { data => $d, line => { stroke => 'yellow' } },
        { data => $d, scatter => { stroke => 'blue' } },
    ],
);

print $g->draw;
