#!/usr/bin/env perl
use strict;
use warnings;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(SVG-Graph-Kit);
use SVG::Graph::Kit;

my $data = [ map { [ $_, $_ * $_ ] } 1 .. 100 ];

my $g = SVG::Graph::Kit->new(data => $data);

print $g->draw;
